# Intoduction to AusTraits, Australia's Plant Trait Database

## AusTraits data records

-   370+ datasets 

-   250+ contributors 

-   1,800,000+ data records 

-   500+ traits 

-   30,000 Australian plant taxa 

## Trait value metadata

Ecological data is only meaningful when each data value is linked to all necessary metadata.\

The following metadata types might be documented:

-   **entity metadata** 

    -   entity type (species, population, individual) 

    -   life stage (adult, seedling, sapling) 

    -   basis of record (field, glasshouse, field experiment) 
    
    -   sex, size, etc.

-   **value metadata** 

    -   value type (mean, minimum, maximum, mode, raw) 

    -   basis of value (measurement, expert observation, literature) 

    -   replicate count 

    -   units 
    
-   **measurement metadata** 

    -   trait collection methods 

-   **location information** 

    -   latitude/longitude 

    -   vegetation description 

    -   location properties, such as 

        -   soil nutrients (soil N)

        -   climate variables (MAT, MAP, aridity index)

        -   fire history (fire intensity, fire severity, years since fire)

-   **context information** 

    *anything recorded about a specific row of data that explains differences between trait values across rows of data* 

    -   entity contexts (*e.g. plant sex, plant age, leaf type measured, tree diameter*) 

    -   treatment contexts (*e.g. nutrient addition treatment, drought treatment*) 

    -   plot contexts (*differences within a single "location"; e.g. slope position, fire history)* 

    -   temporal contexts (*e.g. sampling season, sampling time of day*) 

    -   method contexts (*e.g. canopy position, branch length sampled*) 

-   **taxonomic information** 

    -   genus, family 

    -   full scientific name 

    -   taxon rank 

    -   taxon identifiers (from APC, APNI) 


-   **dataset metadata** 

    -   collection date 

    -   dataset description 

    -   dataset sampling strategy 

    -   dataset citation 

    -   data collectors 


## How to access and use the data



