# About

## Brief overview

Imagine you wanted to build a database of traits. You might start by compiling data from existing datasets, but you'd quickly find that there are many different ways to name and measure the same trait, that different studies use different units, or use an outdated name for a species or taxon.

`traits.build` is a data standard, R package, and workflow that is designed to help you build a harmonised, relational database from disparate datasets. The package was first developed to create [`austraits.build`](https://github.com/traitecoevo/austraits.build/), an open-source database of Australian plant traits. The code has been transformed into a standalone package allowing anyone to build a relational, tabular database for any taxonomic group and any collection of traits.

## How to cite

If you use `traits.build`, please cite:

> Wenk, E., Bal, P., Coleman, D., Gallagher, R., Yang, S., Falster, D. (2024) traits.build: A data model, workflow and R package for building harmonised ecological trait databases. *Ecological Informatics* 83, 102773. <https://doi.org/10.1016/j.ecoinf.2024.102773>

If you use the **AusTraits** dataset, also cite Falster et al. (2021) *Scientific Data* 8:254 (<https://doi.org/10.1038/s41597-021-01006-6>); for the **AusTraits Plant Dictionary** cite Wenk et al. (2024) *Scientific Data* 11:537 (<https://doi.org/10.1038/s41597-024-03368-z>); and for **APCalign** cite Wenk et al. (2024) *Australian Journal of Botany* 72:BT24014 (<https://doi.org/10.1071/BT24014>).


## About this manual

This manual is a step-by-step user guide to the `traits.build` standard, R package and workflow manual. Alongside this manual, you may find the following resources useful:

- [installation instructions](http://traitecoevo.github.io/traits.build/index.html#installation) for the `traits.build` package
- a [reference page with all user-side functions](http://traitecoevo.github.io/traits.build/reference/index.html) for the `traits.build` package. 
- links to [example projects](usage_examples.html)

## A simple example

To get you started, we've provided a template example compilation which you can clone and modify. This provides the basic steps for building a `traits.build` compilation. Follow the instructions in [Tutorials](tutorial_compilation.html) chapter for a step-by-step guide to building a database from scratch.

## Getting help

Along the way, users may encounter a number of errors and warnings. Some of these are designed to help you build a robust database, others may constitue an error in your data, file structure, or the package. If you encounter an error or warning, please read the message carefully and [follow the instructions for getting help](help.html). 

## Acknowledgements

This manual arose from code within the AusTraits project at <https://github.com/traitecoevo/austraits.build>.

AusTraits is a co-investment partnership with the [Australian Research Data Commons](https://ardc.edu.au/) (ARDC) through the Planet Research Data Commons ([DOI: 10.3565/nyk4-4r91](https://doi.org/10.3565/nyk4-4r91)). The ARDC is enabled by the Australian Government's [National Collaborative Research Infrastructure Strategy](https://www.education.gov.au/ncris) (NCRIS). This work received investment ([DP720](https://doi.org/10.47486/DP720)) from the ARDC.

